// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef _VTOP_MKIQROUTERCORESIMPLE_H_
#define _VTOP_MKIQROUTERCORESIMPLE_H_  // guard

#include "verilated_heavy.h"

//==========

class Vtop__Syms;
class Vtop_VerilatedVcd;


//----------

VL_MODULE(Vtop_mkIQRouterCoreSimple) {
  public:
    
    // PORTS
    VL_IN8(CLK,0,0);
    VL_IN8(RST_N,0,0);
    VL_IN8(EN_in_ports_0_putRoutedFlit,0,0);
    VL_IN8(EN_in_ports_0_getNonFullVCs,0,0);
    VL_OUT8(in_ports_0_getNonFullVCs,1,0);
    VL_IN8(EN_in_ports_1_putRoutedFlit,0,0);
    VL_IN8(EN_in_ports_1_getNonFullVCs,0,0);
    VL_OUT8(in_ports_1_getNonFullVCs,1,0);
    VL_IN8(EN_in_ports_2_putRoutedFlit,0,0);
    VL_IN8(EN_in_ports_2_getNonFullVCs,0,0);
    VL_OUT8(in_ports_2_getNonFullVCs,1,0);
    VL_IN8(EN_in_ports_3_putRoutedFlit,0,0);
    VL_IN8(EN_in_ports_3_getNonFullVCs,0,0);
    VL_OUT8(in_ports_3_getNonFullVCs,1,0);
    VL_IN8(EN_in_ports_4_putRoutedFlit,0,0);
    VL_IN8(EN_in_ports_4_getNonFullVCs,0,0);
    VL_OUT8(in_ports_4_getNonFullVCs,1,0);
    VL_IN8(EN_out_ports_0_getFlit,0,0);
    VL_IN8(out_ports_0_putNonFullVCs_nonFullVCs,1,0);
    VL_IN8(EN_out_ports_0_putNonFullVCs,0,0);
    VL_IN8(EN_out_ports_1_getFlit,0,0);
    VL_IN8(out_ports_1_putNonFullVCs_nonFullVCs,1,0);
    VL_IN8(EN_out_ports_1_putNonFullVCs,0,0);
    VL_IN8(EN_out_ports_2_getFlit,0,0);
    VL_IN8(out_ports_2_putNonFullVCs_nonFullVCs,1,0);
    VL_IN8(EN_out_ports_2_putNonFullVCs,0,0);
    VL_IN8(EN_out_ports_3_getFlit,0,0);
    VL_IN8(out_ports_3_putNonFullVCs_nonFullVCs,1,0);
    VL_IN8(EN_out_ports_3_putNonFullVCs,0,0);
    VL_IN8(EN_out_ports_4_getFlit,0,0);
    VL_IN8(out_ports_4_putNonFullVCs_nonFullVCs,1,0);
    VL_IN8(EN_out_ports_4_putNonFullVCs,0,0);
    VL_IN(in_ports_0_putRoutedFlit_flit_in,23,0);
    VL_IN(in_ports_1_putRoutedFlit_flit_in,23,0);
    VL_IN(in_ports_2_putRoutedFlit_flit_in,23,0);
    VL_IN(in_ports_3_putRoutedFlit_flit_in,23,0);
    VL_IN(in_ports_4_putRoutedFlit_flit_in,23,0);
    VL_OUT(out_ports_0_getFlit,20,0);
    VL_OUT(out_ports_1_getFlit,20,0);
    VL_OUT(out_ports_2_getFlit,20,0);
    VL_OUT(out_ports_3_getFlit,20,0);
    VL_OUT(out_ports_4_getFlit,20,0);
    
    // LOCAL SIGNALS
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*2:0*/ __PVT__inPortVL;
        CData/*2:0*/ __PVT__inPortVL_1;
        CData/*2:0*/ __PVT__inPortVL_2;
        CData/*2:0*/ __PVT__inPortVL_3;
        CData/*2:0*/ __PVT__inPortVL_4;
        CData/*0:0*/ __PVT__lockedVL;
        CData/*0:0*/ __PVT__lockedVL_1;
        CData/*0:0*/ __PVT__lockedVL_2;
        CData/*0:0*/ __PVT__lockedVL_3;
        CData/*0:0*/ __PVT__lockedVL_4;
        CData/*0:0*/ __PVT__selectedIO_reg_0;
        CData/*0:0*/ __PVT__selectedIO_reg_0_1;
        CData/*0:0*/ __PVT__selectedIO_reg_0_2;
        CData/*0:0*/ __PVT__selectedIO_reg_0_3;
        CData/*0:0*/ __PVT__selectedIO_reg_0_4;
        CData/*0:0*/ __PVT__selectedIO_reg_1;
        CData/*0:0*/ __PVT__selectedIO_reg_1_1;
        CData/*0:0*/ __PVT__selectedIO_reg_1_2;
        CData/*0:0*/ __PVT__selectedIO_reg_1_3;
        CData/*0:0*/ __PVT__selectedIO_reg_1_4;
        CData/*0:0*/ __PVT__selectedIO_reg_2;
        CData/*0:0*/ __PVT__selectedIO_reg_2_1;
        CData/*0:0*/ __PVT__selectedIO_reg_2_2;
        CData/*0:0*/ __PVT__selectedIO_reg_2_3;
        CData/*0:0*/ __PVT__selectedIO_reg_2_4;
        CData/*0:0*/ __PVT__selectedIO_reg_3;
        CData/*0:0*/ __PVT__selectedIO_reg_3_1;
        CData/*0:0*/ __PVT__selectedIO_reg_3_2;
        CData/*0:0*/ __PVT__selectedIO_reg_3_3;
        CData/*0:0*/ __PVT__selectedIO_reg_3_4;
        CData/*0:0*/ __PVT__selectedIO_reg_4;
        CData/*0:0*/ __PVT__selectedIO_reg_4_1;
        CData/*0:0*/ __PVT__selectedIO_reg_4_2;
        CData/*0:0*/ __PVT__selectedIO_reg_4_3;
        CData/*0:0*/ __PVT__selectedIO_reg_4_4;
        CData/*0:0*/ __PVT__flitBuffers__024EN_enq;
        CData/*2:0*/ __PVT__outPortFIFOs__024first;
        CData/*0:0*/ __PVT__outPortFIFOs__024EN_enq;
        CData/*2:0*/ __PVT__outPortFIFOs_1__024first;
        CData/*2:0*/ __PVT__outPortFIFOs_2__024first;
        CData/*2:0*/ __PVT__outPortFIFOs_3__024first;
        CData/*2:0*/ __PVT__outPortFIFOs_4__024first;
        CData/*0:0*/ __PVT__IF_outPortFIFOs_1_first___05F8_EQ_0_9_THEN_simple___05FETC___05F_d88;
        CData/*0:0*/ __PVT__IF_outPortFIFOs_2_first___05F7_EQ_0_8_THEN_simple___05FETC___05F_d67;
        CData/*0:0*/ __PVT__IF_outPortFIFOs_3_first___05F7_EQ_0_8_THEN_simple___05FETC___05F_d47;
        CData/*0:0*/ __PVT__IF_outPortFIFOs_4_first_EQ_0_THEN_simple_credi_ETC___05F_d27;
        CData/*0:0*/ __PVT__IF_outPortFIFOs_first___05F8_EQ_0_9_THEN_simple_cr_ETC___05F_d108;
        CData/*3:0*/ __PVT__outport_encoder___05F_d828;
        CData/*3:0*/ __PVT__outport_encoder___05F_d829;
        CData/*3:0*/ __PVT__outport_encoder___05F_d830;
        CData/*3:0*/ __PVT__outport_encoder___05F_d831;
        CData/*3:0*/ __PVT__outport_encoder___05F_d832;
        CData/*2:0*/ __PVT__IF_outport_encoder_03_BIT_3_04_THEN_IF_outport_ETC___05F_d693;
        CData/*2:0*/ __PVT__IF_outport_encoder_03_BIT_3_04_THEN_IF_outport_ETC___05F_d694;
        CData/*2:0*/ __PVT__IF_outport_encoder_03_BIT_3_04_THEN_IF_outport_ETC___05F_d695;
        CData/*2:0*/ __PVT__IF_outport_encoder_03_BIT_3_04_THEN_IF_outport_ETC___05F_d696;
        CData/*2:0*/ __PVT__IF_outport_encoder_24_BIT_3_25_THEN_IF_outport_ETC___05F_d689;
        CData/*2:0*/ __PVT__IF_outport_encoder_24_BIT_3_25_THEN_IF_outport_ETC___05F_d690;
        CData/*2:0*/ __PVT__IF_outport_encoder_24_BIT_3_25_THEN_IF_outport_ETC___05F_d691;
        CData/*2:0*/ __PVT__IF_outport_encoder_24_BIT_3_25_THEN_IF_outport_ETC___05F_d692;
        CData/*2:0*/ __PVT__IF_outport_encoder_82_BIT_3_83_THEN_IF_outport_ETC___05F_d697;
        CData/*2:0*/ __PVT__IF_outport_encoder_82_BIT_3_83_THEN_IF_outport_ETC___05F_d698;
        CData/*2:0*/ __PVT__IF_outport_encoder_82_BIT_3_83_THEN_IF_outport_ETC___05F_d699;
        CData/*2:0*/ __PVT__IF_outport_encoder_82_BIT_3_83_THEN_IF_outport_ETC___05F_d700;
    };
    struct {
        CData/*2:0*/ __PVT__active_in___05Fh35433;
        CData/*2:0*/ __PVT__active_in___05Fh36374;
        CData/*2:0*/ __PVT__active_in___05Fh37315;
        CData/*2:0*/ __PVT__active_in___05Fh38256;
        CData/*0:0*/ __PVT__IF_outport_encoder_03_BIT_3_04_THEN_NOT_outpor_ETC___05F_d654;
        CData/*0:0*/ __PVT__IF_outport_encoder_03_BIT_3_04_THEN_NOT_outpor_ETC___05F_d668;
        CData/*0:0*/ __PVT__IF_outport_encoder_03_BIT_3_04_THEN_outport_en_ETC___05F_d652;
        CData/*0:0*/ __PVT__IF_outport_encoder_03_BIT_3_04_THEN_outport_en_ETC___05F_d656;
        CData/*0:0*/ __PVT__IF_outport_encoder_03_BIT_3_04_THEN_outport_en_ETC___05F_d662;
        CData/*0:0*/ __PVT__IF_outport_encoder_03_BIT_3_04_THEN_outport_en_ETC___05F_d669;
        CData/*0:0*/ __PVT__IF_outport_encoder_03_BIT_3_04_THEN_outport_en_ETC___05F_d671;
        CData/*0:0*/ __PVT__IF_outport_encoder_24_BIT_3_25_THEN_NOT_outpor_ETC___05F_d653;
        CData/*0:0*/ __PVT__IF_outport_encoder_24_BIT_3_25_THEN_NOT_outpor_ETC___05F_d665;
        CData/*0:0*/ __PVT__IF_outport_encoder_24_BIT_3_25_THEN_NOT_outpor_ETC___05F_d667;
        CData/*0:0*/ __PVT__IF_outport_encoder_24_BIT_3_25_THEN_outport_en_ETC___05F_d659;
        CData/*0:0*/ __PVT__IF_outport_encoder_24_BIT_3_25_THEN_outport_en_ETC___05F_d663;
        CData/*0:0*/ __PVT__IF_outport_encoder_24_BIT_3_25_THEN_outport_en_ETC___05F_d672;
        CData/*0:0*/ __PVT__IF_outport_encoder_24_BIT_3_25_THEN_outport_en_ETC___05F_d683;
        CData/*0:0*/ __PVT__IF_outport_encoder_24_BIT_3_25_THEN_outport_en_ETC___05F_d685;
        CData/*0:0*/ __PVT__IF_outport_encoder_45_BIT_3_46_THEN_NOT_outpor_ETC___05F_d792;
        CData/*0:0*/ __PVT__IF_outport_encoder_45_BIT_3_46_THEN_NOT_outpor_ETC___05F_d809;
        CData/*0:0*/ __PVT__IF_outport_encoder_45_BIT_3_46_THEN_NOT_outpor_ETC___05F_d810;
        CData/*0:0*/ __PVT__IF_outport_encoder_45_BIT_3_46_THEN_NOT_outpor_ETC___05F_d811;
        CData/*0:0*/ __PVT__IF_outport_encoder_82_BIT_3_83_THEN_outport_en_ETC___05F_d651;
        CData/*0:0*/ __PVT__IF_outport_encoder_82_BIT_3_83_THEN_outport_en_ETC___05F_d655;
        CData/*0:0*/ __PVT__IF_outport_encoder_82_BIT_3_83_THEN_outport_en_ETC___05F_d676;
        CData/*0:0*/ __PVT__IF_outport_encoder_82_BIT_3_83_THEN_outport_en_ETC___05F_d684;
        CData/*0:0*/ __PVT__IF_outport_encoder_82_BIT_3_83_THEN_outport_en_ETC___05F_d686;
        CData/*2:0*/ __PVT__flitBuffers__DOT__inputQueue_ifc_mf_ifc_heads;
        CData/*0:0*/ __PVT__flitBuffers__DOT__inputQueue_ifc_mf_ifc_not_empty;
        CData/*0:0*/ __PVT__flitBuffers__DOT__inputQueue_ifc_mf_ifc_not_full;
        CData/*2:0*/ __PVT__flitBuffers__DOT__inputQueue_ifc_mf_ifc_tails;
        CData/*2:0*/ __PVT__flitBuffers__DOT__x___05Fh1895;
        CData/*2:0*/ __PVT__flitBuffers__DOT__x___05Fh2274;
        CData/*0:0*/ __PVT__flitBuffers__DOT__inputQueue_ifc_mf_ifc_wrFIFO_whas_AND_inputQue_ETC___05F_d20;
        CData/*2:0*/ __PVT__flitBuffers_1__DOT__inputQueue_ifc_mf_ifc_heads;
        CData/*0:0*/ __PVT__flitBuffers_1__DOT__inputQueue_ifc_mf_ifc_not_empty;
        CData/*0:0*/ __PVT__flitBuffers_1__DOT__inputQueue_ifc_mf_ifc_not_full;
        CData/*2:0*/ __PVT__flitBuffers_1__DOT__inputQueue_ifc_mf_ifc_tails;
        CData/*2:0*/ __PVT__flitBuffers_1__DOT__x___05Fh1895;
        CData/*2:0*/ __PVT__flitBuffers_1__DOT__x___05Fh2274;
        CData/*0:0*/ __PVT__flitBuffers_1__DOT__inputQueue_ifc_mf_ifc_wrFIFO_whas_AND_inputQue_ETC___05F_d20;
        CData/*2:0*/ __PVT__flitBuffers_2__DOT__inputQueue_ifc_mf_ifc_heads;
        CData/*0:0*/ __PVT__flitBuffers_2__DOT__inputQueue_ifc_mf_ifc_not_empty;
        CData/*0:0*/ __PVT__flitBuffers_2__DOT__inputQueue_ifc_mf_ifc_not_full;
        CData/*2:0*/ __PVT__flitBuffers_2__DOT__inputQueue_ifc_mf_ifc_tails;
        CData/*2:0*/ __PVT__flitBuffers_2__DOT__x___05Fh1895;
        CData/*2:0*/ __PVT__flitBuffers_2__DOT__x___05Fh2274;
        CData/*0:0*/ __PVT__flitBuffers_2__DOT__inputQueue_ifc_mf_ifc_wrFIFO_whas_AND_inputQue_ETC___05F_d20;
        CData/*2:0*/ __PVT__flitBuffers_3__DOT__inputQueue_ifc_mf_ifc_heads;
        CData/*0:0*/ __PVT__flitBuffers_3__DOT__inputQueue_ifc_mf_ifc_not_empty;
        CData/*0:0*/ __PVT__flitBuffers_3__DOT__inputQueue_ifc_mf_ifc_not_full;
        CData/*2:0*/ __PVT__flitBuffers_3__DOT__inputQueue_ifc_mf_ifc_tails;
        CData/*2:0*/ __PVT__flitBuffers_3__DOT__x___05Fh1895;
        CData/*2:0*/ __PVT__flitBuffers_3__DOT__x___05Fh2274;
        CData/*0:0*/ __PVT__flitBuffers_3__DOT__inputQueue_ifc_mf_ifc_wrFIFO_whas_AND_inputQue_ETC___05F_d20;
        CData/*2:0*/ __PVT__flitBuffers_4__DOT__inputQueue_ifc_mf_ifc_heads;
        CData/*0:0*/ __PVT__flitBuffers_4__DOT__inputQueue_ifc_mf_ifc_not_empty;
        CData/*0:0*/ __PVT__flitBuffers_4__DOT__inputQueue_ifc_mf_ifc_not_full;
        CData/*2:0*/ __PVT__flitBuffers_4__DOT__inputQueue_ifc_mf_ifc_tails;
        CData/*2:0*/ __PVT__flitBuffers_4__DOT__x___05Fh1895;
        CData/*2:0*/ __PVT__flitBuffers_4__DOT__x___05Fh2274;
        CData/*0:0*/ __PVT__flitBuffers_4__DOT__inputQueue_ifc_mf_ifc_wrFIFO_whas_AND_inputQue_ETC___05F_d20;
        CData/*0:0*/ __PVT__outPortFIFOs__DOT__outPortFIFO_ifc_fifo_almost_full;
    };
    struct {
        CData/*0:0*/ __PVT__outPortFIFOs__DOT__outPortFIFO_ifc_fifo_empty;
        CData/*0:0*/ __PVT__outPortFIFOs__DOT__outPortFIFO_ifc_fifo_full;
        CData/*2:0*/ __PVT__outPortFIFOs__DOT__outPortFIFO_ifc_fifo_head;
        CData/*2:0*/ __PVT__outPortFIFOs__DOT__outPortFIFO_ifc_fifo_mem;
        CData/*2:0*/ __PVT__outPortFIFOs__DOT__outPortFIFO_ifc_fifo_mem_1;
        CData/*2:0*/ __PVT__outPortFIFOs__DOT__outPortFIFO_ifc_fifo_mem_2;
        CData/*2:0*/ __PVT__outPortFIFOs__DOT__outPortFIFO_ifc_fifo_mem_3;
        CData/*2:0*/ __PVT__outPortFIFOs__DOT__outPortFIFO_ifc_fifo_mem_4;
        CData/*2:0*/ __PVT__outPortFIFOs__DOT__outPortFIFO_ifc_fifo_mem_5;
        CData/*2:0*/ __PVT__outPortFIFOs__DOT__outPortFIFO_ifc_fifo_mem_6;
        CData/*2:0*/ __PVT__outPortFIFOs__DOT__outPortFIFO_ifc_fifo_mem_7;
        CData/*3:0*/ __PVT__outPortFIFOs__DOT__outPortFIFO_ifc_fifo_size_cnt;
        CData/*2:0*/ __PVT__outPortFIFOs__DOT__outPortFIFO_ifc_fifo_tail;
        CData/*3:0*/ __PVT__outPortFIFOs__DOT__IF_outPortFIFO_ifc_fifo_w_deq_whas_AND_outPort_ETC___05F_d48;
        CData/*2:0*/ __PVT__outPortFIFOs__DOT__outPortFIFO_ifc_fifo_head_PLUS_1___05F_d110;
        CData/*2:0*/ __PVT__outPortFIFOs__DOT__outPortFIFO_ifc_fifo_tail_PLUS_1___05F_d111;
        CData/*0:0*/ __PVT__outPortFIFOs__DOT__IF_outPortFIFO_ifc_fifo_w_deq_whas_AND_outPort_ETC___05F_d115;
        CData/*0:0*/ __PVT__outPortFIFOs__DOT__IF_outPortFIFO_ifc_fifo_w_deq_whas_AND_outPort_ETC___05F_d33;
        CData/*0:0*/ __PVT__outPortFIFOs__DOT__IF_outPortFIFO_ifc_fifo_w_deq_whas_AND_outPort_ETC___05F_d41;
        CData/*0:0*/ __PVT__outPortFIFOs_1__DOT__outPortFIFO_ifc_fifo_almost_full;
        CData/*0:0*/ __PVT__outPortFIFOs_1__DOT__outPortFIFO_ifc_fifo_empty;
        CData/*0:0*/ __PVT__outPortFIFOs_1__DOT__outPortFIFO_ifc_fifo_full;
        CData/*2:0*/ __PVT__outPortFIFOs_1__DOT__outPortFIFO_ifc_fifo_head;
        CData/*2:0*/ __PVT__outPortFIFOs_1__DOT__outPortFIFO_ifc_fifo_mem;
        CData/*2:0*/ __PVT__outPortFIFOs_1__DOT__outPortFIFO_ifc_fifo_mem_1;
        CData/*2:0*/ __PVT__outPortFIFOs_1__DOT__outPortFIFO_ifc_fifo_mem_2;
        CData/*2:0*/ __PVT__outPortFIFOs_1__DOT__outPortFIFO_ifc_fifo_mem_3;
        CData/*2:0*/ __PVT__outPortFIFOs_1__DOT__outPortFIFO_ifc_fifo_mem_4;
        CData/*2:0*/ __PVT__outPortFIFOs_1__DOT__outPortFIFO_ifc_fifo_mem_5;
        CData/*2:0*/ __PVT__outPortFIFOs_1__DOT__outPortFIFO_ifc_fifo_mem_6;
        CData/*2:0*/ __PVT__outPortFIFOs_1__DOT__outPortFIFO_ifc_fifo_mem_7;
        CData/*3:0*/ __PVT__outPortFIFOs_1__DOT__outPortFIFO_ifc_fifo_size_cnt;
        CData/*2:0*/ __PVT__outPortFIFOs_1__DOT__outPortFIFO_ifc_fifo_tail;
        CData/*3:0*/ __PVT__outPortFIFOs_1__DOT__IF_outPortFIFO_ifc_fifo_w_deq_whas_AND_outPort_ETC___05F_d48;
        CData/*3:0*/ __PVT__outPortFIFOs_1__DOT__IF_outPortFIFO_ifc_fifo_w_deq_whas_THEN_outPor_ETC___05F_d47;
        CData/*2:0*/ __PVT__outPortFIFOs_1__DOT__outPortFIFO_ifc_fifo_head_PLUS_1___05F_d110;
        CData/*2:0*/ __PVT__outPortFIFOs_1__DOT__outPortFIFO_ifc_fifo_tail_PLUS_1___05F_d111;
        CData/*0:0*/ __PVT__outPortFIFOs_1__DOT__IF_outPortFIFO_ifc_fifo_w_deq_whas_AND_outPort_ETC___05F_d115;
        CData/*0:0*/ __PVT__outPortFIFOs_1__DOT__IF_outPortFIFO_ifc_fifo_w_deq_whas_AND_outPort_ETC___05F_d33;
        CData/*0:0*/ __PVT__outPortFIFOs_1__DOT__IF_outPortFIFO_ifc_fifo_w_deq_whas_AND_outPort_ETC___05F_d41;
        CData/*0:0*/ __PVT__outPortFIFOs_1__DOT__IF_outPortFIFO_ifc_fifo_w_deq_whas_THEN_outPor_ETC___05F_d32;
        CData/*0:0*/ __PVT__outPortFIFOs_1__DOT__IF_outPortFIFO_ifc_fifo_w_deq_whas_THEN_outPor_ETC___05F_d40;
        CData/*0:0*/ __PVT__outPortFIFOs_2__DOT__outPortFIFO_ifc_fifo_almost_full;
        CData/*0:0*/ __PVT__outPortFIFOs_2__DOT__outPortFIFO_ifc_fifo_empty;
        CData/*0:0*/ __PVT__outPortFIFOs_2__DOT__outPortFIFO_ifc_fifo_full;
        CData/*2:0*/ __PVT__outPortFIFOs_2__DOT__outPortFIFO_ifc_fifo_head;
        CData/*2:0*/ __PVT__outPortFIFOs_2__DOT__outPortFIFO_ifc_fifo_mem;
        CData/*2:0*/ __PVT__outPortFIFOs_2__DOT__outPortFIFO_ifc_fifo_mem_1;
        CData/*2:0*/ __PVT__outPortFIFOs_2__DOT__outPortFIFO_ifc_fifo_mem_2;
        CData/*2:0*/ __PVT__outPortFIFOs_2__DOT__outPortFIFO_ifc_fifo_mem_3;
        CData/*2:0*/ __PVT__outPortFIFOs_2__DOT__outPortFIFO_ifc_fifo_mem_4;
        CData/*2:0*/ __PVT__outPortFIFOs_2__DOT__outPortFIFO_ifc_fifo_mem_5;
        CData/*2:0*/ __PVT__outPortFIFOs_2__DOT__outPortFIFO_ifc_fifo_mem_6;
        CData/*2:0*/ __PVT__outPortFIFOs_2__DOT__outPortFIFO_ifc_fifo_mem_7;
        CData/*3:0*/ __PVT__outPortFIFOs_2__DOT__outPortFIFO_ifc_fifo_size_cnt;
        CData/*2:0*/ __PVT__outPortFIFOs_2__DOT__outPortFIFO_ifc_fifo_tail;
        CData/*3:0*/ __PVT__outPortFIFOs_2__DOT__IF_outPortFIFO_ifc_fifo_w_deq_whas_AND_outPort_ETC___05F_d48;
        CData/*3:0*/ __PVT__outPortFIFOs_2__DOT__IF_outPortFIFO_ifc_fifo_w_deq_whas_THEN_outPor_ETC___05F_d47;
        CData/*2:0*/ __PVT__outPortFIFOs_2__DOT__outPortFIFO_ifc_fifo_head_PLUS_1___05F_d110;
        CData/*2:0*/ __PVT__outPortFIFOs_2__DOT__outPortFIFO_ifc_fifo_tail_PLUS_1___05F_d111;
        CData/*0:0*/ __PVT__outPortFIFOs_2__DOT__IF_outPortFIFO_ifc_fifo_w_deq_whas_AND_outPort_ETC___05F_d115;
        CData/*0:0*/ __PVT__outPortFIFOs_2__DOT__IF_outPortFIFO_ifc_fifo_w_deq_whas_AND_outPort_ETC___05F_d33;
        CData/*0:0*/ __PVT__outPortFIFOs_2__DOT__IF_outPortFIFO_ifc_fifo_w_deq_whas_AND_outPort_ETC___05F_d41;
        CData/*0:0*/ __PVT__outPortFIFOs_2__DOT__IF_outPortFIFO_ifc_fifo_w_deq_whas_THEN_outPor_ETC___05F_d32;
    };
    struct {
        CData/*0:0*/ __PVT__outPortFIFOs_2__DOT__IF_outPortFIFO_ifc_fifo_w_deq_whas_THEN_outPor_ETC___05F_d40;
        CData/*0:0*/ __PVT__outPortFIFOs_3__DOT__outPortFIFO_ifc_fifo_almost_full;
        CData/*0:0*/ __PVT__outPortFIFOs_3__DOT__outPortFIFO_ifc_fifo_empty;
        CData/*0:0*/ __PVT__outPortFIFOs_3__DOT__outPortFIFO_ifc_fifo_full;
        CData/*2:0*/ __PVT__outPortFIFOs_3__DOT__outPortFIFO_ifc_fifo_head;
        CData/*2:0*/ __PVT__outPortFIFOs_3__DOT__outPortFIFO_ifc_fifo_mem;
        CData/*2:0*/ __PVT__outPortFIFOs_3__DOT__outPortFIFO_ifc_fifo_mem_1;
        CData/*2:0*/ __PVT__outPortFIFOs_3__DOT__outPortFIFO_ifc_fifo_mem_2;
        CData/*2:0*/ __PVT__outPortFIFOs_3__DOT__outPortFIFO_ifc_fifo_mem_3;
        CData/*2:0*/ __PVT__outPortFIFOs_3__DOT__outPortFIFO_ifc_fifo_mem_4;
        CData/*2:0*/ __PVT__outPortFIFOs_3__DOT__outPortFIFO_ifc_fifo_mem_5;
        CData/*2:0*/ __PVT__outPortFIFOs_3__DOT__outPortFIFO_ifc_fifo_mem_6;
        CData/*2:0*/ __PVT__outPortFIFOs_3__DOT__outPortFIFO_ifc_fifo_mem_7;
        CData/*3:0*/ __PVT__outPortFIFOs_3__DOT__outPortFIFO_ifc_fifo_size_cnt;
        CData/*2:0*/ __PVT__outPortFIFOs_3__DOT__outPortFIFO_ifc_fifo_tail;
        CData/*3:0*/ __PVT__outPortFIFOs_3__DOT__IF_outPortFIFO_ifc_fifo_w_deq_whas_AND_outPort_ETC___05F_d48;
        CData/*3:0*/ __PVT__outPortFIFOs_3__DOT__IF_outPortFIFO_ifc_fifo_w_deq_whas_THEN_outPor_ETC___05F_d47;
        CData/*2:0*/ __PVT__outPortFIFOs_3__DOT__outPortFIFO_ifc_fifo_head_PLUS_1___05F_d110;
        CData/*2:0*/ __PVT__outPortFIFOs_3__DOT__outPortFIFO_ifc_fifo_tail_PLUS_1___05F_d111;
        CData/*0:0*/ __PVT__outPortFIFOs_3__DOT__IF_outPortFIFO_ifc_fifo_w_deq_whas_AND_outPort_ETC___05F_d115;
        CData/*0:0*/ __PVT__outPortFIFOs_3__DOT__IF_outPortFIFO_ifc_fifo_w_deq_whas_AND_outPort_ETC___05F_d33;
        CData/*0:0*/ __PVT__outPortFIFOs_3__DOT__IF_outPortFIFO_ifc_fifo_w_deq_whas_AND_outPort_ETC___05F_d41;
        CData/*0:0*/ __PVT__outPortFIFOs_3__DOT__IF_outPortFIFO_ifc_fifo_w_deq_whas_THEN_outPor_ETC___05F_d32;
        CData/*0:0*/ __PVT__outPortFIFOs_3__DOT__IF_outPortFIFO_ifc_fifo_w_deq_whas_THEN_outPor_ETC___05F_d40;
        CData/*0:0*/ __PVT__outPortFIFOs_4__DOT__outPortFIFO_ifc_fifo_almost_full;
        CData/*0:0*/ __PVT__outPortFIFOs_4__DOT__outPortFIFO_ifc_fifo_empty;
        CData/*0:0*/ __PVT__outPortFIFOs_4__DOT__outPortFIFO_ifc_fifo_full;
        CData/*2:0*/ __PVT__outPortFIFOs_4__DOT__outPortFIFO_ifc_fifo_head;
        CData/*2:0*/ __PVT__outPortFIFOs_4__DOT__outPortFIFO_ifc_fifo_mem;
        CData/*2:0*/ __PVT__outPortFIFOs_4__DOT__outPortFIFO_ifc_fifo_mem_1;
        CData/*2:0*/ __PVT__outPortFIFOs_4__DOT__outPortFIFO_ifc_fifo_mem_2;
        CData/*2:0*/ __PVT__outPortFIFOs_4__DOT__outPortFIFO_ifc_fifo_mem_3;
        CData/*2:0*/ __PVT__outPortFIFOs_4__DOT__outPortFIFO_ifc_fifo_mem_4;
        CData/*2:0*/ __PVT__outPortFIFOs_4__DOT__outPortFIFO_ifc_fifo_mem_5;
        CData/*2:0*/ __PVT__outPortFIFOs_4__DOT__outPortFIFO_ifc_fifo_mem_6;
        CData/*2:0*/ __PVT__outPortFIFOs_4__DOT__outPortFIFO_ifc_fifo_mem_7;
        CData/*3:0*/ __PVT__outPortFIFOs_4__DOT__outPortFIFO_ifc_fifo_size_cnt;
        CData/*2:0*/ __PVT__outPortFIFOs_4__DOT__outPortFIFO_ifc_fifo_tail;
        CData/*3:0*/ __PVT__outPortFIFOs_4__DOT__IF_outPortFIFO_ifc_fifo_w_deq_whas_AND_outPort_ETC___05F_d48;
        CData/*3:0*/ __PVT__outPortFIFOs_4__DOT__IF_outPortFIFO_ifc_fifo_w_deq_whas_THEN_outPor_ETC___05F_d47;
        CData/*2:0*/ __PVT__outPortFIFOs_4__DOT__outPortFIFO_ifc_fifo_head_PLUS_1___05F_d110;
        CData/*2:0*/ __PVT__outPortFIFOs_4__DOT__outPortFIFO_ifc_fifo_tail_PLUS_1___05F_d111;
        CData/*0:0*/ __PVT__outPortFIFOs_4__DOT__IF_outPortFIFO_ifc_fifo_w_deq_whas_AND_outPort_ETC___05F_d115;
        CData/*0:0*/ __PVT__outPortFIFOs_4__DOT__IF_outPortFIFO_ifc_fifo_w_deq_whas_AND_outPort_ETC___05F_d33;
        CData/*0:0*/ __PVT__outPortFIFOs_4__DOT__IF_outPortFIFO_ifc_fifo_w_deq_whas_AND_outPort_ETC___05F_d41;
        CData/*0:0*/ __PVT__outPortFIFOs_4__DOT__IF_outPortFIFO_ifc_fifo_w_deq_whas_THEN_outPor_ETC___05F_d32;
        CData/*0:0*/ __PVT__outPortFIFOs_4__DOT__IF_outPortFIFO_ifc_fifo_w_deq_whas_THEN_outPor_ETC___05F_d40;
        CData/*0:0*/ __PVT__routerAlloc__DOT__as_inputArbGrants_reg_0;
        CData/*0:0*/ __PVT__routerAlloc__DOT__as_inputArbGrants_reg_0_1;
        CData/*0:0*/ __PVT__routerAlloc__DOT__as_inputArbGrants_reg_0_2;
        CData/*0:0*/ __PVT__routerAlloc__DOT__as_inputArbGrants_reg_0_3;
        CData/*0:0*/ __PVT__routerAlloc__DOT__as_inputArbGrants_reg_0_4;
        CData/*0:0*/ __PVT__routerAlloc__DOT__as_inputArbGrants_reg_1;
        CData/*0:0*/ __PVT__routerAlloc__DOT__as_inputArbGrants_reg_1_1;
        CData/*0:0*/ __PVT__routerAlloc__DOT__as_inputArbGrants_reg_1_2;
        CData/*0:0*/ __PVT__routerAlloc__DOT__as_inputArbGrants_reg_1_3;
        CData/*0:0*/ __PVT__routerAlloc__DOT__as_inputArbGrants_reg_1_4;
        CData/*0:0*/ __PVT__routerAlloc__DOT__as_inputArbGrants_reg_2;
        CData/*0:0*/ __PVT__routerAlloc__DOT__as_inputArbGrants_reg_2_1;
        CData/*0:0*/ __PVT__routerAlloc__DOT__as_inputArbGrants_reg_2_2;
        CData/*0:0*/ __PVT__routerAlloc__DOT__as_inputArbGrants_reg_2_3;
        CData/*0:0*/ __PVT__routerAlloc__DOT__as_inputArbGrants_reg_2_4;
        CData/*0:0*/ __PVT__routerAlloc__DOT__as_inputArbGrants_reg_3;
        CData/*0:0*/ __PVT__routerAlloc__DOT__as_inputArbGrants_reg_3_1;
    };
    struct {
        CData/*0:0*/ __PVT__routerAlloc__DOT__as_inputArbGrants_reg_3_2;
        CData/*0:0*/ __PVT__routerAlloc__DOT__as_inputArbGrants_reg_3_3;
        CData/*0:0*/ __PVT__routerAlloc__DOT__as_inputArbGrants_reg_3_4;
        CData/*0:0*/ __PVT__routerAlloc__DOT__as_inputArbGrants_reg_4;
        CData/*0:0*/ __PVT__routerAlloc__DOT__as_inputArbGrants_reg_4_1;
        CData/*0:0*/ __PVT__routerAlloc__DOT__as_inputArbGrants_reg_4_2;
        CData/*0:0*/ __PVT__routerAlloc__DOT__as_inputArbGrants_reg_4_3;
        CData/*0:0*/ __PVT__routerAlloc__DOT__as_inputArbGrants_reg_4_4;
        CData/*4:0*/ __PVT__routerAlloc__DOT__inputArbs__024input_arbs_0_select;
        CData/*4:0*/ __PVT__routerAlloc__DOT__inputArbs__024input_arbs_1_select;
        CData/*4:0*/ __PVT__routerAlloc__DOT__inputArbs__024input_arbs_2_select;
        CData/*4:0*/ __PVT__routerAlloc__DOT__inputArbs__024input_arbs_3_select;
        CData/*4:0*/ __PVT__routerAlloc__DOT__inputArbs__024input_arbs_4_select;
        CData/*4:0*/ __PVT__routerAlloc__DOT__outputArbs__024output_arbs_0_select;
        CData/*4:0*/ __PVT__routerAlloc__DOT__outputArbs__024output_arbs_0_select_requests;
        CData/*4:0*/ __PVT__routerAlloc__DOT__outputArbs__024output_arbs_1_select;
        CData/*4:0*/ __PVT__routerAlloc__DOT__outputArbs__024output_arbs_1_select_requests;
        CData/*4:0*/ __PVT__routerAlloc__DOT__outputArbs__024output_arbs_2_select;
        CData/*4:0*/ __PVT__routerAlloc__DOT__outputArbs__024output_arbs_2_select_requests;
        CData/*4:0*/ __PVT__routerAlloc__DOT__outputArbs__024output_arbs_3_select;
        CData/*4:0*/ __PVT__routerAlloc__DOT__outputArbs__024output_arbs_3_select_requests;
        CData/*4:0*/ __PVT__routerAlloc__DOT__outputArbs__024output_arbs_4_select;
        CData/*4:0*/ __PVT__routerAlloc__DOT__outputArbs__024output_arbs_4_select_requests;
        CData/*4:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ias_0_token;
        CData/*4:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ias_0_token__024D_IN;
        CData/*4:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ias_1_token;
        CData/*4:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ias_1_token__024D_IN;
        CData/*4:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ias_2_token;
        CData/*4:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ias_2_token__024D_IN;
        CData/*4:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ias_3_token;
        CData/*4:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ias_3_token__024D_IN;
        CData/*4:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ias_4_token;
        CData/*4:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ias_4_token__024D_IN;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh12572;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh12587;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh12602;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh12617;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh12632;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh14013;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh14460;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh14853;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh15197;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh15492;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh19612;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh19627;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh19642;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh19657;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh19672;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh21053;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh21500;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh21893;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh22237;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh22532;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh26652;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh26667;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh26682;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh26697;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh26712;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh28093;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh28540;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh28933;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh29277;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh29572;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh33692;
    };
    struct {
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh33707;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh33722;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh33737;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh33752;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh35133;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh35580;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh35973;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh36317;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh36612;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh5532;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh5547;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh5562;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh5577;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh5592;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh6973;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh7420;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh7813;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh8157;
        CData/*1:0*/ __PVT__routerAlloc__DOT__inputArbs__DOT__ab___05Fh8452;
        CData/*4:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__oas_0_token;
        CData/*4:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__oas_0_token__024D_IN;
        CData/*4:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__oas_1_token;
        CData/*4:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__oas_1_token__024D_IN;
        CData/*4:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__oas_2_token;
        CData/*4:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__oas_2_token__024D_IN;
        CData/*4:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__oas_3_token;
        CData/*4:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__oas_3_token__024D_IN;
        CData/*4:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__oas_4_token;
        CData/*4:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__oas_4_token__024D_IN;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh12572;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh12587;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh12602;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh12617;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh12632;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh14013;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh14460;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh14853;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh15197;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh15492;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh19612;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh19627;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh19642;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh19657;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh19672;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh21053;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh21500;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh21893;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh22237;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh22532;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh26652;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh26667;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh26682;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh26697;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh26712;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh28093;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh28540;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh28933;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh29277;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh29572;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh33692;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh33707;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh33722;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh33737;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh33752;
    };
    struct {
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh35133;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh35580;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh35973;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh36317;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh36612;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh5532;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh5547;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh5562;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh5577;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh5592;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh6973;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh7420;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh7813;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh8157;
        CData/*1:0*/ __PVT__routerAlloc__DOT__outputArbs__DOT__ab___05Fh8452;
        IData/*24:0*/ __PVT__routerAlloc__024allocate;
        IData/*24:0*/ __PVT__routerAlloc__024allocate_alloc_input;
        IData/*19:0*/ __PVT__flitBuffers__DOT__inputQueue_ifc_mf_ifc_fifoMem__024D_OUT;
        IData/*19:0*/ __PVT__flitBuffers_1__DOT__inputQueue_ifc_mf_ifc_fifoMem__024D_OUT;
        IData/*19:0*/ __PVT__flitBuffers_2__DOT__inputQueue_ifc_mf_ifc_fifoMem__024D_OUT;
        IData/*19:0*/ __PVT__flitBuffers_3__DOT__inputQueue_ifc_mf_ifc_fifoMem__024D_OUT;
        IData/*19:0*/ __PVT__flitBuffers_4__DOT__inputQueue_ifc_mf_ifc_fifoMem__024D_OUT;
        QData/*63:0*/ __PVT__outPortFIFOs__DOT__outPortFIFO_ifc_fifo_deq_cnt;
        QData/*63:0*/ __PVT__outPortFIFOs__DOT__outPortFIFO_ifc_fifo_enq_cnt;
        QData/*63:0*/ __PVT__outPortFIFOs__DOT__x___05Fh1275;
        QData/*63:0*/ __PVT__outPortFIFOs__DOT__x___05Fh2099;
        QData/*63:0*/ __PVT__outPortFIFOs_1__DOT__outPortFIFO_ifc_fifo_deq_cnt;
        QData/*63:0*/ __PVT__outPortFIFOs_1__DOT__outPortFIFO_ifc_fifo_enq_cnt;
        QData/*63:0*/ __PVT__outPortFIFOs_1__DOT__x___05Fh1275;
        QData/*63:0*/ __PVT__outPortFIFOs_1__DOT__x___05Fh2099;
        QData/*63:0*/ __PVT__outPortFIFOs_2__DOT__outPortFIFO_ifc_fifo_deq_cnt;
        QData/*63:0*/ __PVT__outPortFIFOs_2__DOT__outPortFIFO_ifc_fifo_enq_cnt;
        QData/*63:0*/ __PVT__outPortFIFOs_2__DOT__x___05Fh1275;
        QData/*63:0*/ __PVT__outPortFIFOs_2__DOT__x___05Fh2099;
        QData/*63:0*/ __PVT__outPortFIFOs_3__DOT__outPortFIFO_ifc_fifo_deq_cnt;
        QData/*63:0*/ __PVT__outPortFIFOs_3__DOT__outPortFIFO_ifc_fifo_enq_cnt;
        QData/*63:0*/ __PVT__outPortFIFOs_3__DOT__x___05Fh1275;
        QData/*63:0*/ __PVT__outPortFIFOs_3__DOT__x___05Fh2099;
        QData/*63:0*/ __PVT__outPortFIFOs_4__DOT__outPortFIFO_ifc_fifo_deq_cnt;
        QData/*63:0*/ __PVT__outPortFIFOs_4__DOT__outPortFIFO_ifc_fifo_enq_cnt;
        QData/*63:0*/ __PVT__outPortFIFOs_4__DOT__x___05Fh1275;
        QData/*63:0*/ __PVT__outPortFIFOs_4__DOT__x___05Fh2099;
        IData/*19:0*/ __PVT__flitBuffers__DOT__inputQueue_ifc_mf_ifc_fifoMem__DOT__arr[8];
        IData/*19:0*/ __PVT__flitBuffers_1__DOT__inputQueue_ifc_mf_ifc_fifoMem__DOT__arr[8];
        IData/*19:0*/ __PVT__flitBuffers_2__DOT__inputQueue_ifc_mf_ifc_fifoMem__DOT__arr[8];
        IData/*19:0*/ __PVT__flitBuffers_3__DOT__inputQueue_ifc_mf_ifc_fifoMem__DOT__arr[8];
        IData/*19:0*/ __PVT__flitBuffers_4__DOT__inputQueue_ifc_mf_ifc_fifoMem__DOT__arr[8];
    };
    
    // LOCAL VARIABLES
    CData/*2:0*/ __Vdlyvdim0__flitBuffers__DOT__inputQueue_ifc_mf_ifc_fifoMem__DOT__arr__v0;
    CData/*0:0*/ __Vdlyvset__flitBuffers__DOT__inputQueue_ifc_mf_ifc_fifoMem__DOT__arr__v0;
    CData/*2:0*/ __Vdlyvdim0__flitBuffers_1__DOT__inputQueue_ifc_mf_ifc_fifoMem__DOT__arr__v0;
    CData/*0:0*/ __Vdlyvset__flitBuffers_1__DOT__inputQueue_ifc_mf_ifc_fifoMem__DOT__arr__v0;
    CData/*2:0*/ __Vdlyvdim0__flitBuffers_2__DOT__inputQueue_ifc_mf_ifc_fifoMem__DOT__arr__v0;
    CData/*0:0*/ __Vdlyvset__flitBuffers_2__DOT__inputQueue_ifc_mf_ifc_fifoMem__DOT__arr__v0;
    CData/*2:0*/ __Vdlyvdim0__flitBuffers_3__DOT__inputQueue_ifc_mf_ifc_fifoMem__DOT__arr__v0;
    CData/*0:0*/ __Vdlyvset__flitBuffers_3__DOT__inputQueue_ifc_mf_ifc_fifoMem__DOT__arr__v0;
    CData/*2:0*/ __Vdlyvdim0__flitBuffers_4__DOT__inputQueue_ifc_mf_ifc_fifoMem__DOT__arr__v0;
    CData/*0:0*/ __Vdlyvset__flitBuffers_4__DOT__inputQueue_ifc_mf_ifc_fifoMem__DOT__arr__v0;
    IData/*19:0*/ __Vdlyvval__flitBuffers__DOT__inputQueue_ifc_mf_ifc_fifoMem__DOT__arr__v0;
    IData/*19:0*/ __Vdlyvval__flitBuffers_1__DOT__inputQueue_ifc_mf_ifc_fifoMem__DOT__arr__v0;
    IData/*19:0*/ __Vdlyvval__flitBuffers_2__DOT__inputQueue_ifc_mf_ifc_fifoMem__DOT__arr__v0;
    IData/*19:0*/ __Vdlyvval__flitBuffers_3__DOT__inputQueue_ifc_mf_ifc_fifoMem__DOT__arr__v0;
    IData/*19:0*/ __Vdlyvval__flitBuffers_4__DOT__inputQueue_ifc_mf_ifc_fifoMem__DOT__arr__v0;
    QData/*34:0*/ __Vtablechg1[2];
    QData/*34:0*/ __Vtablechg2[2];
    QData/*34:0*/ __Vtablechg3[2];
    QData/*34:0*/ __Vtablechg4[2];
    static CData/*2:0*/ __Vtable1___PVT__inPortVL[2];
    static CData/*2:0*/ __Vtable1___PVT__inPortVL_1[2];
    static CData/*2:0*/ __Vtable1___PVT__inPortVL_2[2];
    static CData/*2:0*/ __Vtable1___PVT__inPortVL_3[2];
    static CData/*2:0*/ __Vtable1___PVT__inPortVL_4[2];
    static CData/*0:0*/ __Vtable1___PVT__lockedVL[2];
    static CData/*0:0*/ __Vtable1___PVT__lockedVL_1[2];
    static CData/*0:0*/ __Vtable1___PVT__lockedVL_2[2];
    static CData/*0:0*/ __Vtable1___PVT__lockedVL_3[2];
    static CData/*0:0*/ __Vtable1___PVT__lockedVL_4[2];
    static CData/*0:0*/ __Vtable1___PVT__selectedIO_reg_0[2];
    static CData/*0:0*/ __Vtable1___PVT__selectedIO_reg_0_1[2];
    static CData/*0:0*/ __Vtable1___PVT__selectedIO_reg_0_2[2];
    static CData/*0:0*/ __Vtable1___PVT__selectedIO_reg_0_3[2];
    static CData/*0:0*/ __Vtable1___PVT__selectedIO_reg_0_4[2];
    static CData/*0:0*/ __Vtable1___PVT__selectedIO_reg_1[2];
    static CData/*0:0*/ __Vtable1___PVT__selectedIO_reg_1_1[2];
    static CData/*0:0*/ __Vtable1___PVT__selectedIO_reg_1_2[2];
    static CData/*0:0*/ __Vtable1___PVT__selectedIO_reg_1_3[2];
    static CData/*0:0*/ __Vtable1___PVT__selectedIO_reg_1_4[2];
    static CData/*0:0*/ __Vtable1___PVT__selectedIO_reg_2[2];
    static CData/*0:0*/ __Vtable1___PVT__selectedIO_reg_2_1[2];
    static CData/*0:0*/ __Vtable1___PVT__selectedIO_reg_2_2[2];
    static CData/*0:0*/ __Vtable1___PVT__selectedIO_reg_2_3[2];
    static CData/*0:0*/ __Vtable1___PVT__selectedIO_reg_2_4[2];
    static CData/*0:0*/ __Vtable1___PVT__selectedIO_reg_3[2];
    static CData/*0:0*/ __Vtable1___PVT__selectedIO_reg_3_1[2];
    static CData/*0:0*/ __Vtable1___PVT__selectedIO_reg_3_2[2];
    static CData/*0:0*/ __Vtable1___PVT__selectedIO_reg_3_3[2];
    static CData/*0:0*/ __Vtable1___PVT__selectedIO_reg_3_4[2];
    static CData/*0:0*/ __Vtable1___PVT__selectedIO_reg_4[2];
    static CData/*0:0*/ __Vtable1___PVT__selectedIO_reg_4_1[2];
    static CData/*0:0*/ __Vtable1___PVT__selectedIO_reg_4_2[2];
    static CData/*0:0*/ __Vtable1___PVT__selectedIO_reg_4_3[2];
    static CData/*0:0*/ __Vtable1___PVT__selectedIO_reg_4_4[2];
    static CData/*2:0*/ __Vtable2___PVT__inPortVL[2];
    static CData/*2:0*/ __Vtable2___PVT__inPortVL_1[2];
    static CData/*2:0*/ __Vtable2___PVT__inPortVL_2[2];
    static CData/*2:0*/ __Vtable2___PVT__inPortVL_3[2];
    static CData/*2:0*/ __Vtable2___PVT__inPortVL_4[2];
    static CData/*0:0*/ __Vtable2___PVT__lockedVL[2];
    static CData/*0:0*/ __Vtable2___PVT__lockedVL_1[2];
    static CData/*0:0*/ __Vtable2___PVT__lockedVL_2[2];
    static CData/*0:0*/ __Vtable2___PVT__lockedVL_3[2];
    static CData/*0:0*/ __Vtable2___PVT__lockedVL_4[2];
    static CData/*0:0*/ __Vtable2___PVT__selectedIO_reg_0[2];
    static CData/*0:0*/ __Vtable2___PVT__selectedIO_reg_0_1[2];
    static CData/*0:0*/ __Vtable2___PVT__selectedIO_reg_0_2[2];
    static CData/*0:0*/ __Vtable2___PVT__selectedIO_reg_0_3[2];
    static CData/*0:0*/ __Vtable2___PVT__selectedIO_reg_0_4[2];
    static CData/*0:0*/ __Vtable2___PVT__selectedIO_reg_1[2];
    static CData/*0:0*/ __Vtable2___PVT__selectedIO_reg_1_1[2];
    static CData/*0:0*/ __Vtable2___PVT__selectedIO_reg_1_2[2];
    static CData/*0:0*/ __Vtable2___PVT__selectedIO_reg_1_3[2];
    static CData/*0:0*/ __Vtable2___PVT__selectedIO_reg_1_4[2];
    static CData/*0:0*/ __Vtable2___PVT__selectedIO_reg_2[2];
    static CData/*0:0*/ __Vtable2___PVT__selectedIO_reg_2_1[2];
    static CData/*0:0*/ __Vtable2___PVT__selectedIO_reg_2_2[2];
    static CData/*0:0*/ __Vtable2___PVT__selectedIO_reg_2_3[2];
    static CData/*0:0*/ __Vtable2___PVT__selectedIO_reg_2_4[2];
    static CData/*0:0*/ __Vtable2___PVT__selectedIO_reg_3[2];
    static CData/*0:0*/ __Vtable2___PVT__selectedIO_reg_3_1[2];
    static CData/*0:0*/ __Vtable2___PVT__selectedIO_reg_3_2[2];
    static CData/*0:0*/ __Vtable2___PVT__selectedIO_reg_3_3[2];
    static CData/*0:0*/ __Vtable2___PVT__selectedIO_reg_3_4[2];
    static CData/*0:0*/ __Vtable2___PVT__selectedIO_reg_4[2];
    static CData/*0:0*/ __Vtable2___PVT__selectedIO_reg_4_1[2];
    static CData/*0:0*/ __Vtable2___PVT__selectedIO_reg_4_2[2];
    static CData/*0:0*/ __Vtable2___PVT__selectedIO_reg_4_3[2];
    static CData/*0:0*/ __Vtable2___PVT__selectedIO_reg_4_4[2];
    static CData/*2:0*/ __Vtable3___PVT__inPortVL[2];
    static CData/*2:0*/ __Vtable3___PVT__inPortVL_1[2];
    static CData/*2:0*/ __Vtable3___PVT__inPortVL_2[2];
    static CData/*2:0*/ __Vtable3___PVT__inPortVL_3[2];
    static CData/*2:0*/ __Vtable3___PVT__inPortVL_4[2];
    static CData/*0:0*/ __Vtable3___PVT__lockedVL[2];
    static CData/*0:0*/ __Vtable3___PVT__lockedVL_1[2];
    static CData/*0:0*/ __Vtable3___PVT__lockedVL_2[2];
    static CData/*0:0*/ __Vtable3___PVT__lockedVL_3[2];
    static CData/*0:0*/ __Vtable3___PVT__lockedVL_4[2];
    static CData/*0:0*/ __Vtable3___PVT__selectedIO_reg_0[2];
    static CData/*0:0*/ __Vtable3___PVT__selectedIO_reg_0_1[2];
    static CData/*0:0*/ __Vtable3___PVT__selectedIO_reg_0_2[2];
    static CData/*0:0*/ __Vtable3___PVT__selectedIO_reg_0_3[2];
    static CData/*0:0*/ __Vtable3___PVT__selectedIO_reg_0_4[2];
    static CData/*0:0*/ __Vtable3___PVT__selectedIO_reg_1[2];
    static CData/*0:0*/ __Vtable3___PVT__selectedIO_reg_1_1[2];
    static CData/*0:0*/ __Vtable3___PVT__selectedIO_reg_1_2[2];
    static CData/*0:0*/ __Vtable3___PVT__selectedIO_reg_1_3[2];
    static CData/*0:0*/ __Vtable3___PVT__selectedIO_reg_1_4[2];
    static CData/*0:0*/ __Vtable3___PVT__selectedIO_reg_2[2];
    static CData/*0:0*/ __Vtable3___PVT__selectedIO_reg_2_1[2];
    static CData/*0:0*/ __Vtable3___PVT__selectedIO_reg_2_2[2];
    static CData/*0:0*/ __Vtable3___PVT__selectedIO_reg_2_3[2];
    static CData/*0:0*/ __Vtable3___PVT__selectedIO_reg_2_4[2];
    static CData/*0:0*/ __Vtable3___PVT__selectedIO_reg_3[2];
    static CData/*0:0*/ __Vtable3___PVT__selectedIO_reg_3_1[2];
    static CData/*0:0*/ __Vtable3___PVT__selectedIO_reg_3_2[2];
    static CData/*0:0*/ __Vtable3___PVT__selectedIO_reg_3_3[2];
    static CData/*0:0*/ __Vtable3___PVT__selectedIO_reg_3_4[2];
    static CData/*0:0*/ __Vtable3___PVT__selectedIO_reg_4[2];
    static CData/*0:0*/ __Vtable3___PVT__selectedIO_reg_4_1[2];
    static CData/*0:0*/ __Vtable3___PVT__selectedIO_reg_4_2[2];
    static CData/*0:0*/ __Vtable3___PVT__selectedIO_reg_4_3[2];
    static CData/*0:0*/ __Vtable3___PVT__selectedIO_reg_4_4[2];
    static CData/*2:0*/ __Vtable4___PVT__inPortVL[2];
    static CData/*2:0*/ __Vtable4___PVT__inPortVL_1[2];
    static CData/*2:0*/ __Vtable4___PVT__inPortVL_2[2];
    static CData/*2:0*/ __Vtable4___PVT__inPortVL_3[2];
    static CData/*2:0*/ __Vtable4___PVT__inPortVL_4[2];
    static CData/*0:0*/ __Vtable4___PVT__lockedVL[2];
    static CData/*0:0*/ __Vtable4___PVT__lockedVL_1[2];
    static CData/*0:0*/ __Vtable4___PVT__lockedVL_2[2];
    static CData/*0:0*/ __Vtable4___PVT__lockedVL_3[2];
    static CData/*0:0*/ __Vtable4___PVT__lockedVL_4[2];
    static CData/*0:0*/ __Vtable4___PVT__selectedIO_reg_0[2];
    static CData/*0:0*/ __Vtable4___PVT__selectedIO_reg_0_1[2];
    static CData/*0:0*/ __Vtable4___PVT__selectedIO_reg_0_2[2];
    static CData/*0:0*/ __Vtable4___PVT__selectedIO_reg_0_3[2];
    static CData/*0:0*/ __Vtable4___PVT__selectedIO_reg_0_4[2];
    static CData/*0:0*/ __Vtable4___PVT__selectedIO_reg_1[2];
    static CData/*0:0*/ __Vtable4___PVT__selectedIO_reg_1_1[2];
    static CData/*0:0*/ __Vtable4___PVT__selectedIO_reg_1_2[2];
    static CData/*0:0*/ __Vtable4___PVT__selectedIO_reg_1_3[2];
    static CData/*0:0*/ __Vtable4___PVT__selectedIO_reg_1_4[2];
    static CData/*0:0*/ __Vtable4___PVT__selectedIO_reg_2[2];
    static CData/*0:0*/ __Vtable4___PVT__selectedIO_reg_2_1[2];
    static CData/*0:0*/ __Vtable4___PVT__selectedIO_reg_2_2[2];
    static CData/*0:0*/ __Vtable4___PVT__selectedIO_reg_2_3[2];
    static CData/*0:0*/ __Vtable4___PVT__selectedIO_reg_2_4[2];
    static CData/*0:0*/ __Vtable4___PVT__selectedIO_reg_3[2];
    static CData/*0:0*/ __Vtable4___PVT__selectedIO_reg_3_1[2];
    static CData/*0:0*/ __Vtable4___PVT__selectedIO_reg_3_2[2];
    static CData/*0:0*/ __Vtable4___PVT__selectedIO_reg_3_3[2];
    static CData/*0:0*/ __Vtable4___PVT__selectedIO_reg_3_4[2];
    static CData/*0:0*/ __Vtable4___PVT__selectedIO_reg_4[2];
    static CData/*0:0*/ __Vtable4___PVT__selectedIO_reg_4_1[2];
    static CData/*0:0*/ __Vtable4___PVT__selectedIO_reg_4_2[2];
    static CData/*0:0*/ __Vtable4___PVT__selectedIO_reg_4_3[2];
    static CData/*0:0*/ __Vtable4___PVT__selectedIO_reg_4_4[2];
    
    // INTERNAL VARIABLES
  private:
    Vtop__Syms* __VlSymsp;  // Symbol table
  public:
    
    // CONSTRUCTORS
  private:
    VL_UNCOPYABLE(Vtop_mkIQRouterCoreSimple);  ///< Copying not allowed
  public:
    Vtop_mkIQRouterCoreSimple(const char* name = "TOP");
    ~Vtop_mkIQRouterCoreSimple();
    
    // INTERNAL METHODS
    void __Vconfigure(Vtop__Syms* symsp, bool first);
  private:
    void _ctor_var_reset() VL_ATTR_COLD;
  public:
    void _initial__TOP__top__DOT__if_wrapper_noc_2x2_16_inst__DOT__mkNetworkSimple_inst__DOT__net_routers_router_core_1__2(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _initial__TOP__top__DOT__if_wrapper_noc_2x2_16_inst__DOT__mkNetworkSimple_inst__DOT__net_routers_router_core_2__3(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _initial__TOP__top__DOT__if_wrapper_noc_2x2_16_inst__DOT__mkNetworkSimple_inst__DOT__net_routers_router_core_3__4(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _initial__TOP__top__DOT__if_wrapper_noc_2x2_16_inst__DOT__mkNetworkSimple_inst__DOT__net_routers_router_core__1(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _sequent__TOP__top__DOT__if_wrapper_noc_2x2_16_inst__DOT__mkNetworkSimple_inst__DOT__net_routers_router_core_1__10(Vtop__Syms* __restrict vlSymsp);
    void _sequent__TOP__top__DOT__if_wrapper_noc_2x2_16_inst__DOT__mkNetworkSimple_inst__DOT__net_routers_router_core_1__12(Vtop__Syms* __restrict vlSymsp);
    void _sequent__TOP__top__DOT__if_wrapper_noc_2x2_16_inst__DOT__mkNetworkSimple_inst__DOT__net_routers_router_core_1__17(Vtop__Syms* __restrict vlSymsp);
    void _sequent__TOP__top__DOT__if_wrapper_noc_2x2_16_inst__DOT__mkNetworkSimple_inst__DOT__net_routers_router_core_1__6(Vtop__Syms* __restrict vlSymsp);
    void _sequent__TOP__top__DOT__if_wrapper_noc_2x2_16_inst__DOT__mkNetworkSimple_inst__DOT__net_routers_router_core_2__11(Vtop__Syms* __restrict vlSymsp);
    void _sequent__TOP__top__DOT__if_wrapper_noc_2x2_16_inst__DOT__mkNetworkSimple_inst__DOT__net_routers_router_core_2__13(Vtop__Syms* __restrict vlSymsp);
    void _sequent__TOP__top__DOT__if_wrapper_noc_2x2_16_inst__DOT__mkNetworkSimple_inst__DOT__net_routers_router_core_2__18(Vtop__Syms* __restrict vlSymsp);
    void _sequent__TOP__top__DOT__if_wrapper_noc_2x2_16_inst__DOT__mkNetworkSimple_inst__DOT__net_routers_router_core_2__7(Vtop__Syms* __restrict vlSymsp);
    void _sequent__TOP__top__DOT__if_wrapper_noc_2x2_16_inst__DOT__mkNetworkSimple_inst__DOT__net_routers_router_core_3__15(Vtop__Syms* __restrict vlSymsp);
    void _sequent__TOP__top__DOT__if_wrapper_noc_2x2_16_inst__DOT__mkNetworkSimple_inst__DOT__net_routers_router_core_3__16(Vtop__Syms* __restrict vlSymsp);
    void _sequent__TOP__top__DOT__if_wrapper_noc_2x2_16_inst__DOT__mkNetworkSimple_inst__DOT__net_routers_router_core_3__8(Vtop__Syms* __restrict vlSymsp);
    void _sequent__TOP__top__DOT__if_wrapper_noc_2x2_16_inst__DOT__mkNetworkSimple_inst__DOT__net_routers_router_core__14(Vtop__Syms* __restrict vlSymsp);
    void _sequent__TOP__top__DOT__if_wrapper_noc_2x2_16_inst__DOT__mkNetworkSimple_inst__DOT__net_routers_router_core__19(Vtop__Syms* __restrict vlSymsp);
    void _sequent__TOP__top__DOT__if_wrapper_noc_2x2_16_inst__DOT__mkNetworkSimple_inst__DOT__net_routers_router_core__5(Vtop__Syms* __restrict vlSymsp);
    void _sequent__TOP__top__DOT__if_wrapper_noc_2x2_16_inst__DOT__mkNetworkSimple_inst__DOT__net_routers_router_core__9(Vtop__Syms* __restrict vlSymsp);
    void _settle__TOP__top__DOT__if_wrapper_noc_2x2_16_inst__DOT__mkNetworkSimple_inst__DOT__net_routers_router_core_1__21(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__top__DOT__if_wrapper_noc_2x2_16_inst__DOT__mkNetworkSimple_inst__DOT__net_routers_router_core_1__24(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__top__DOT__if_wrapper_noc_2x2_16_inst__DOT__mkNetworkSimple_inst__DOT__net_routers_router_core_2__22(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__top__DOT__if_wrapper_noc_2x2_16_inst__DOT__mkNetworkSimple_inst__DOT__net_routers_router_core_2__25(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__top__DOT__if_wrapper_noc_2x2_16_inst__DOT__mkNetworkSimple_inst__DOT__net_routers_router_core_3__23(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__top__DOT__if_wrapper_noc_2x2_16_inst__DOT__mkNetworkSimple_inst__DOT__net_routers_router_core__20(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void traceInit(VerilatedVcd* vcdp, void* userthis, uint32_t code);
    static void traceFull(VerilatedVcd* vcdp, void* userthis, uint32_t code);
    static void traceChg(VerilatedVcd* vcdp, void* userthis, uint32_t code);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);

//----------


#endif  // guard
